// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using thub.DataAcess.Data;

#nullable disable

namespace thub.DataAcess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240426131055_AddTournamentsTabl")]
    partial class AddTournamentsTabl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("thub.Models.TeamModel", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            Name = "Fnatic"
                        },
                        new
                        {
                            TeamId = 2,
                            Name = "G2"
                        },
                        new
                        {
                            TeamId = 3,
                            Name = "Faze Clan"
                        });
                });

            modelBuilder.Entity("thub.Models.TournamentModel", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NumberOfGroups")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfTeams")
                        .HasColumnType("int");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("TournamentId");

                    b.ToTable("Tournaments");

                    b.HasData(
                        new
                        {
                            TournamentId = 1,
                            Name = "Mešane dvojice",
                            NumberOfGroups = 2,
                            NumberOfTeams = 8,
                            Sport = "Beach Volleyball",
                            StartDate = new DateOnly(2024, 5, 20)
                        },
                        new
                        {
                            TournamentId = 2,
                            Name = "Dvojice",
                            NumberOfGroups = 2,
                            NumberOfTeams = 8,
                            Sport = "Beach Volleyball",
                            StartDate = new DateOnly(2024, 6, 22)
                        },
                        new
                        {
                            TournamentId = 3,
                            Name = "Mešane dvojice",
                            NumberOfGroups = 2,
                            NumberOfTeams = 8,
                            Sport = "Beach Volleyball",
                            StartDate = new DateOnly(2024, 8, 5)
                        });
                });

            modelBuilder.Entity("thub.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "sergej.ajlec@gmail.com",
                            LastName = "Ajlec",
                            Name = "Sergej",
                            Password = "test123"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "dejan.ajlec@gmail.com",
                            LastName = "Ajlec",
                            Name = "Dejan",
                            Password = "test123"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "samo.ajlec@gmail.com",
                            LastName = "Ajlec",
                            Name = "Samo",
                            Password = "test123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
